services:
  image-processor:
    build: .
    container_name: vinvinvin-image-processor
    #restart: unless-stopped
    restart: no

    environment:
      - TZ=Asia/Seoul

    volumes:
      - ./config:/app/config
      - /home/ubuntu/docker/php_alpine_8.2/images:/app/images
